# Generated by Django 4.2.1 on 2023-06-13 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, upload_to='WelcomeDanceShop photos/goods')),
                ('size', models.PositiveSmallIntegerField()),
                ('label', models.CharField(max_length=150)),
                ('price', models.PositiveSmallIntegerField()),
                ('color', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=255)),
            ],
        ),
    ]
