# Generated by Django 4.2.1 on 2023-06-13 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_gender_rubric_goods_gender_goods_rubric'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gender',
            options={'verbose_name_plural': 'Пол'},
        ),
        migrations.AlterModelOptions(
            name='goods',
            options={'verbose_name_plural': 'Товары'},
        ),
        migrations.AlterModelOptions(
            name='rubric',
            options={'verbose_name_plural': 'Рубрики'},
        ),
    ]
