# Generated by Django 4.2.1 on 2023-06-14 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_goods_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='rubric',
            name='slug',
            field=models.SlugField(max_length=255, null=True, verbose_name='rubric_URL'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, verbose_name='URL'),
        ),
    ]
