# Generated by Django 4.2.1 on 2023-06-14 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0005_rubric_slug_alter_goods_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rubric',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, verbose_name='rubric_URL'),
        ),
    ]
