# Generated by Django 4.2.1 on 2023-07-19 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0008_goods_available'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gender',
            options={'verbose_name': 'пол', 'verbose_name_plural': 'Пол'},
        ),
        migrations.AlterModelOptions(
            name='goods',
            options={'ordering': ['-rubric', 'color'], 'verbose_name': 'товары', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AlterModelOptions(
            name='rubric',
            options={'verbose_name': 'рубрики', 'verbose_name_plural': 'Рубрики'},
        ),
        migrations.AlterField(
            model_name='gender',
            name='gender',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='available',
            field=models.BooleanField(default=True, verbose_name='В наличии'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='category',
            field=models.CharField(max_length=255, verbose_name='Предназначено'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='color',
            field=models.CharField(max_length=100, verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='content',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='gender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='goods.gender', verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='label',
            field=models.CharField(max_length=150, verbose_name='Фирма'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='photo',
            field=models.ImageField(blank=True, upload_to='WelcomeDanceShop photos/goods', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='price',
            field=models.PositiveSmallIntegerField(verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='quantity',
            field=models.PositiveSmallIntegerField(null=1, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='rubric',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='goods.rubric', verbose_name='Рубрика'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='size',
            field=models.PositiveSmallIntegerField(verbose_name='Размер'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='rubric',
            name='name',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Название'),
        ),
    ]
