# Generated by Django 4.2.1 on 2023-07-21 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0009_alter_gender_options_alter_goods_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=10, verbose_name='Количество'),
        ),
    ]
