# Generated by Django 4.2.1 on 2023-08-09 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0010_alter_goods_quantity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goods',
            options={'ordering': ['-rubric', 'color', 'pk'], 'verbose_name': 'товары', 'verbose_name_plural': 'Товары'},
        ),
    ]
