# Generated by Django 4.2.1 on 2023-07-14 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_alter_cartitem_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
