# Generated by Django 4.2.1 on 2023-06-19 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goods', '0006_alter_rubric_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='LetterForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('let_title', models.CharField(blank=True, max_length=255, verbose_name='Тема письма')),
                ('let_content', models.CharField(max_length=255, verbose_name='Текст письма')),
                ('let_email', models.EmailField(max_length=254, verbose_name='Отправитель')),
                ('let_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.rubric', verbose_name='Категория товара')),
            ],
            options={
                'verbose_name_plural': 'Письма',
            },
        ),
    ]
