# Generated by Django 4.2.1 on 2023-06-15 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_alter_articles_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='slug',
            field=models.SlugField(max_length=255, null=True, verbose_name='article_URL'),
        ),
    ]
