# Generated by Django 4.2.1 on 2023-06-19 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_articles_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, verbose_name='article_URL'),
        ),
    ]
