# Generated by Django 4.2.1 on 2023-06-21 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_alter_articles_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='content2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='articles',
            name='content3',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='articles',
            name='content4',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='articles',
            name='photo1',
            field=models.ImageField(blank=True, upload_to='WelcomeDanceShop photos/articles'),
        ),
    ]
